### ISSUE TITLE
Errors on compile

### ISSUE THREAD

**Issue by Alcor17** [suculent/APDS9900_Ambient_Light_and_Proximity_Sensor#1]
Hello.
I tried compile some of examples but ever there are errors. First error is:

ProximitySensor:47:14: error: 'D1' was not declared in this scope

   Wire.begin(D1, D2); // A4, A5 is default for Arduino

When I fix it changing D1 and D2, the next error is:

..\Arduino\libraries\APDS9900_Ambient_Light_and_Proximity_Sensor-master\src\APDS9900.cpp:1084:10: error: 'uint16' was not declared in this scope

   val = (uint16)(input[0] + 256 * input[1]);

How to solve these errors? Thanks.

**Comment by suculent** [comment]
uint16 should be defined somewhere in Arduino.h and D1/D2 somewhere in board configuration. Seems like none of those was found on your system?

1. #include <Arduino.h>

2. select board and memory/SPIFFS configuration

What’s your board?

**Comment by Alcor17** [comment]
The board is Arduino UNO

I've included the line number one but the compilations errors continue.

**Comment by suculent** [comment]
I can try it on Arduino Nano / Mini Pro, but I’m a bit too busy to play with it today.

Those are generic errors you have. It should be same with every empty Sketch.

You can try to replace uint16_t with “word” but the first is more correct and descriptive.

What version of Arduino Core do you have?

M.

**Comment by Alcor17** [comment]
Thanks for your answers.

I proved with an empty sketch as you suggested, and there was not errors, in anothers sketches either.

Arduino Ide version is 1.8.8 and Arduino AVR boards 1.6.22

**Comment by suculent** [comment]
Hmm, now I see the typo in there. It should have been `uint16_t` and not just `uint16`. Thanks for the report. Closed in https://github.com/suculent/APDS9900_Ambient_Light_and_Proximity_Sensor/commit/25ea14f2936c4ddd97b8a321b3dac048e202dcad
